### ISSUE TITLE
stream.on option 

### ISSUE THREAD

**Issue by TentacleSama4254** [FreeTubeApp/yt-channel-info#27]
Is it possible to add a stream.on option wich fetches video info pa's soon as a video is posted (for specified channels)
Simmilar to the twitter  api

**Comment by GilgusMaximus** [comment]
No. This is not possible. As the description of the module states, we are not using the API. We are scraping the web page. Therefore we have no information on when a new video is posted. You'd have to run it as a periodic event in your application to check whether new videos are available. But doing this too often will eventually lead to your ip getting blocked for some time, due to the amount of traffic you generate. This will then result in 429 error codes.
