### ISSUE TITLE
What should i mention in place of channelIdType ?

### ISSUE THREAD

**Issue by Yuvraj102** [FreeTubeApp/yt-channel-info#40]
I am new to this package ,i tried the very first method mentioned in the [docs ](https://www.npmjs.com/package/yt-channel-info) i.e. getChannelInfo 
Below is my code 
I dont know what to pass as channelIdType ? 
``` 
function getInfo(){
    ytch.getChannelInfo(channelId,typeof channelId)
.then((response)=>{
    console.log('channel response: ',response)
})
.catch((err)=>{
    console.log('err in fetching channel info: ',err)
})
```
I get a Network error for this code 
here is my channel id if in case you need ``` UCDq3WZuqMw_IiagOtcAS_oQ ```
i tried with the channel id mentioned in doc and passed ```0``` as type but still the same error additionally i get some cors policy message in my console

**Comment by GilgusMaximus** [comment]
The channelIdType is an optional parameter. If you do not know how to use it, now worries, just leave it out. I added the option to allow faster and more efficient network usage by allowing developers to incorporated additional knowledge about the channel id.
Because, as stated in the ReadMe, the channel id for one channel differs for all the different possible urls. So knowing which type it is saves time to test all possibilities. But this is more towards power users who already have their project running and want to improve their code as much as possible.

A correct call, here with await/async instead of then/catch, could look like this:

![image](https://user-images.githubusercontent.com/34301369/128079882-bade07ab-991b-4eb4-8898-8cf830acfbf8.png)

![image](https://user-images.githubusercontent.com/34301369/128079461-d50ccd41-2c4e-4feb-bf62-d0788791964b.png)

**Comment by Yuvraj102** [comment]
Yeah this code works thank you , and Awesome package ✨
