### ISSUE TITLE
Downgrading to v2

### ISSUE THREAD

**Issue by MistakingManx** [FreeTubeApp/yt-channel-info#59]
I have to specify v2 when using this package, because it errors relentlessly with v3, I'm not quite sure why.

**Comment by ChunkyProgrammer** [comment]
V3 changed the way that the methods are called. You now have to pass an object as a parameter.


Ex:

```js 
const payload = {
   channelId: 'UCXuqSBlHAE6Xw-yeJA0Tunw', // Required
   channelIdType: 0,
   httpsAgent: agent
}

ytch.getChannelInfo(payload).then((response) => {
   if (!response.alertMessage) {
      console.log(response)
   } else {
      console.log('Channel could not be found.')
      // throw response.alertMessage
   }
}).catch((err) => {
   console.log(err)
})
```

You can look at the updated README for changes to the other methods

**Comment by MistakingManx** [comment]
Yeah I figured that out super quickly, but it errors regardless, it didn't even reference my files in the errors!

**Comment by ChunkyProgrammer** [comment]
This PR might fix the issue you're having: https://github.com/FreeTubeApp/yt-channel-info/pull/61

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
