### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by thelastspark** [FreeTubeApp/yt-channel-info#8]
So I'm getting a 429 error, however, I request maybe 10 channels/minute - is that too much using this module or is it something else? Moreover, is there a way to use cookies/auth-token to prevent the rate-limiting?

**Comment by PrestonN** [comment]
There probably isn't anything that can be done on my end to prevent to rate limiting, since that's something that YouTube does automatically.  The rate limiting is based on your IP so even if I added any sort of authentication (which is outside of the scope of this project), you'll probably get rate limited anyways.

There's a couple of things that you can do to prevent the rate limiting, though these all depend on your use case:

- YouTube provides RSS feeds which could be used in place of `getChannelVideos`, though these feeds don't provide as much information as the endpoint we're using.
- You can use a VPN / Proxy to bypass the rate limiting
- You can simply wait a little bit for the ban to be lifted (I've heard anywhere from a couple to 24 hours)

Unfortunately, Google controls the rate limiting and there isn't anything I can do on my end.  Getting around it is something that will have to be considered within your project.  Apologies for the inconvenience.
